
(function(){
  const STORAGE_KEY='skinlog_mvp_mobile_v1';
  const PHOTO_LIMIT=10;
  const BODY_PARTS=[['face','얼굴'],['neck','목'],['arm','팔'],['leg','다리'],['trunk','몸통'],['hand','손'],['foot','발'],['other','기타']];
  const SLEEP=[['','선택 안 함'],['good','좋음'],['normal','보통'],['bad','나쁨']];
  const DEFAULT={onboardingCompleted:false,profile:null,records:[]};
  let state=load(); let tab='home'; let draft=null; let detailId=null; let reportRange=7; let guardianMemo='';
  const root=document.getElementById('root');
  function showToast(message){
    let toast=document.getElementById('skinlogToast');
    if(!toast){
      toast=document.createElement('div');
      toast.id='skinlogToast';
      toast.style.cssText='position:fixed;left:50%;bottom:88px;transform:translateX(-50%);z-index:9999;max-width:360px;width:calc(100% - 32px);background:#0f172a;color:white;padding:14px 16px;border-radius:18px;text-align:center;font-weight:800;box-shadow:0 16px 40px rgba(15,23,42,.25);opacity:0;transition:opacity .2s ease';
      document.body.appendChild(toast);
    }
    toast.textContent=message;
    toast.style.opacity='1';
    clearTimeout(showToast.timer);
    showToast.timer=setTimeout(()=>{toast.style.opacity='0'},1800);
  }
  root.addEventListener('click',(event)=>{
    const navButton=event.target.closest('[data-tab]');
    if(!navButton||!root.contains(navButton))return;
    event.preventDefault();
    event.stopPropagation();
    tab=navButton.dataset.tab;
    detailId=null;
    draft=null;
    render();
  });
  function uid(p='id'){return `${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
  function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch(e){return DEFAULT}}
  function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return true}catch(e){console.warn('스킨로그 저장 실패',e);return false}}
  function setState(next){state=typeof next==='function'?next(state):next;const ok=persist();render();return ok}
  function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
  function todayInput(){const n=new Date();return new Date(n.getTime()-n.getTimezoneOffset()*60000).toISOString().slice(0,16)}
  function fmt(v,only=false){if(!v)return '-';const d=new Date(v);if(isNaN(d))return v;return new Intl.DateTimeFormat('ko-KR',only?{month:'long',day:'numeric',weekday:'short'}:{year:'numeric',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}).format(d)}
  function daysAgo(v){if(!v)return '기록 없음';const d=new Date(v),t=new Date();const a=new Date(t.getFullYear(),t.getMonth(),t.getDate()),b=new Date(d.getFullYear(),d.getMonth(),d.getDate());const diff=Math.round((a-b)/86400000);return diff===0?'오늘':diff===1?'1일 전':`${diff}일 전`}
  function partLabel(k){return (BODY_PARTS.find(x=>x[0]===k)||[,k])[1]}
  function sleepLabel(k){return (SLEEP.find(x=>x[0]===k)||[,'-'])[1]}
  function avg(arr){const v=arr.filter(n=>typeof n==='number'&&!isNaN(n));return v.length?Number((v.reduce((a,b)=>a+b,0)/v.length).toFixed(1)):0}
  function inDays(r,days){const d=new Date(r.recordedAt);if(isNaN(d))return false;const n=new Date();const s=new Date(n);s.setDate(n.getDate()-days+1);s.setHours(0,0,0,0);return d>=s&&d<=n}
  function emptyRecord(){return {id:uid('record'),recordedAt:todayInput(),bodyParts:[],photos:[],symptoms:{itchScore:0,rednessScore:0,oozeScore:0,scaleScore:0,scratchScore:0},medicines:'',foodMemo:'',sleepStatus:'',note:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
  function imageFileToDataUrl(file){return new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>{const original=String(reader.result||'');const img=new Image();img.onload=()=>{try{const max=1200;let w=img.width,h=img.height;if(w>max||h>max){const ratio=Math.min(max/w,max/h);w=Math.round(w*ratio);h=Math.round(h*ratio)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',0.72))}catch(e){resolve(original)}};img.onerror=()=>resolve(original);img.src=original};reader.onerror=()=>resolve('');reader.readAsDataURL(file)})}
  function normalizeImport(parsed){if(!parsed||typeof parsed!=='object')throw new Error('invalid');const profile=parsed.profile||parsed?.data?.profile||null;const records=Array.isArray(parsed.records)?parsed.records:(Array.isArray(parsed?.data?.records)?parsed.data.records:[]);if(!profile&&!records.length)throw new Error('invalid');return {...DEFAULT,...parsed,onboardingCompleted:true,profile,records}}
  function header(title,back=false,right=''){return `<header class="header"><div>${back?`<button class="icon-btn" data-action="back">‹</button>`:''}</div><h2>${title}</h2><div>${right}</div></header>`}
  function nav(){return `<nav class="nav">${[['home','⌂','오늘 기록'],['records','□','기록 보기'],['report','▥','리포트'],['settings','⚙','설정']].map(([k,i,l])=>`<button class="${tab===k?'active':''}" data-tab="${k}"><span class="ico">${i}</span><span>${l}</span></button>`).join('')}</nav>`}
  function app(body){return `<div class="app">${body}${nav()}</div>`}
  function input(label,id,value='',placeholder='',type='text'){return `<label><span class="label">${label}</span><input id="${id}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}"></label>`}
  function textarea(label,id,value='',placeholder=''){return `<label><span class="label">${label}</span><textarea id="${id}" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`}
  function onboarding(){root.innerHTML=`<div class="center-screen"><div class="welcome"><div class="title"><div class="logo">◇</div><h1>스킨로그</h1><p>병원에 보여주는 피부 기록장</p></div><div class="notice"><b>사용 전 안내</b>이 앱은 피부 상태를 기록하고 진료 상담 시 참고하기 위한 도구입니다. 질병의 진단, 치료, 처방을 제공하지 않습니다.</div><button class="btn" id="startBtn">시작하기</button><p class="tiny muted" style="text-align:center;margin-top:14px;line-height:1.6">정확한 진단과 치료는 의사 또는 의료 전문가와 상담해 주세요.</p></div></div>`;document.getElementById('startBtn').onclick=()=>setState(s=>({...s,onboardingCompleted:true}))}
  function profile(){root.innerHTML=`<div class="app" style="padding-bottom:0">${header('프로필 생성')}<div class="content"><div class="seg"><button id="typeSelf" class="choice">♙ 본인</button><button id="typeChild" class="choice active">☺ 아이</button></div>${input('이름/별명','nickname','','예) 지우')}${input('생년월일 또는 나이대','birthInfo','','예) 2018.05 또는 7세')}${textarea('피부질환 메모','skinMemo','','예) 결절성 양진 치료 경험, 아토피 병력 등')}<button class="btn" id="saveProfile">저장</button></div></div>`;let type='child';document.getElementById('typeSelf').onclick=()=>{type='self';document.getElementById('typeSelf').classList.add('active');document.getElementById('typeChild').classList.remove('active')};document.getElementById('typeChild').onclick=()=>{type='child';document.getElementById('typeChild').classList.add('active');document.getElementById('typeSelf').classList.remove('active')};document.getElementById('saveProfile').onclick=()=>{const nickname=document.getElementById('nickname').value.trim();if(!nickname){alert('이름 또는 별명을 입력해 주세요.');return}setState(s=>({...s,profile:{id:uid('profile'),type,nickname,birthInfo:document.getElementById('birthInfo').value.trim(),skinMemo:document.getElementById('skinMemo').value.trim(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}))}}
  function home(){const sorted=[...state.records].sort((a,b)=>new Date(b.recordedAt)-new Date(a.recordedAt));const latest=sorted[0];const last7=state.records.filter(r=>inDays(r,7));const avgItch=avg(last7.map(r=>r.symptoms.itchScore));const med=latest?.medicines||'-';root.innerHTML=app(`${header('오늘 기록')}<div class="content"><div class="card row"><div class="avatar">${state.profile?.type==='child'?'🙂':'👤'}</div><div class="grow"><h2>${esc(state.profile?.nickname||'프로필')}</h2><p class="small muted" style="margin-top:4px">최근 기록: ${daysAgo(latest?.recordedAt)}</p><p style="margin-top:10px"><span class="pill">상태: ${latest?(latest.symptoms.itchScore>=7||latest.symptoms.rednessScore>=7?'심한 편':'보통'):'기록 전'}</span></p></div></div><button class="btn" id="newRecord" style="height:64px;border-radius:26px;font-size:18px">✎ 오늘 기록하기</button><div class="grid3"><div class="card summary"><p class="tiny muted bold">최근 기록</p><p class="value">${latest?daysAgo(latest.recordedAt):'없음'}</p><p class="tiny muted">${latest?fmt(latest.recordedAt,true):'-'}</p></div><div class="card summary"><p class="tiny muted bold">가려움 평균</p><p class="value">${avgItch}</p><p class="tiny muted">최근 7일 / 10</p></div><div class="card summary"><p class="tiny muted bold">최근 사용한 약</p><p class="value">${esc(med.slice(0,8)||'-')}</p><p class="tiny muted">${med.length>8?'자세히 보기':''}</p></div></div><div class="card soft"><p class="bold">1차 MVP 안내</p><p class="small muted" style="margin-top:6px;line-height:1.6">현재 버전은 스마트폰 브라우저 저장소를 사용하는 테스트용입니다. 중요한 기록은 설정에서 JSON 백업을 저장해 주세요.</p></div></div>`);document.getElementById('newRecord').onclick=()=>{draft=emptyRecord();tab='form';render()}}
  function form(){const isEdit=state.records.some(r=>r.id===draft?.id);root.innerHTML=app(`${header(isEdit?'기록 수정':'기록 작성',true)}<div class="content">${isEdit?'<div class="card soft"><p class="small bold">수정 모드</p><p class="tiny muted" style="margin-top:6px;line-height:1.5">기존 기록을 불러왔습니다. 내용을 바꾼 뒤 아래의 수정 저장 버튼을 눌러주세요.</p></div>':''}${input('기록 시간','recordedAt',draft.recordedAt,'','datetime-local')}<section><div class="row" style="justify-content:space-between;margin-bottom:8px"><b class="small">사진</b><span class="tiny muted">최대 10장</span></div><label class="photo-box">▧<span>+ 사진 추가</span><input id="photoInput" type="file" accept="image/*" multiple></label><div class="photos" id="photos"></div></section><section><b class="small">부위 선택</b><div class="grid4" style="margin-top:10px">${BODY_PARTS.map(([k,l])=>`<button class="chip ${draft.bodyParts.includes(k)?'active':''}" data-part="${k}">${l}</button>`).join('')}</div></section><section><b class="small">증상 점수</b><div style="display:flex;flex-direction:column;gap:12px;margin-top:10px">${score('가려움','itchScore')}${score('붉음','rednessScore')}${score('진물','oozeScore')}${score('각질','scaleScore')}${score('긁음','scratchScore')}</div></section>${input('오늘 사용한 약 / 보습제','medicines',draft.medicines,'예) 보습제, 스테로이드 연고')}${input('오늘 먹은 특이 음식','foodMemo',draft.foodMemo,'예) 딸기, 초콜릿, 우유')}<label><span class="label">수면 상태</span><select id="sleepStatus">${SLEEP.map(([k,l])=>`<option value="${k}" ${draft.sleepStatus===k?'selected':''}>${l}</option>`).join('')}</select></label>${textarea('메모','note',draft.note,'예) 밤에 가려워서 자주 깸')}<button class="btn" id="saveRecord">✓ ${isEdit?'수정 저장':'기록 저장'}</button></div>`);drawPhotos();bindForm()}
  function score(label,key){return `<div class="score"><div class="score-head"><b>${label}</b><span class="score-val" id="val-${key}">${draft.symptoms[key]||0} / 10</span></div><input type="range" min="0" max="10" value="${draft.symptoms[key]||0}" data-score="${key}"><div class="row tiny muted" style="justify-content:space-between"><span>없음</span><span>심함</span></div></div>`}
  function syncDraft(){['recordedAt','medicines','foodMemo','sleepStatus','note'].forEach(id=>{const el=document.getElementById(id);if(el)draft[id]=el.value});draft.updatedAt=new Date().toISOString()}
  function drawPhotos(){const box=document.getElementById('photos');if(!box)return;box.innerHTML=draft.photos.map(p=>`<div class="photo"><img src="${p.dataUrl}" alt="피부 기록"><button data-photo-del="${p.id}">×</button></div>`).join('');box.querySelectorAll('[data-photo-del]').forEach(b=>b.onclick=()=>{draft.photos=draft.photos.filter(p=>p.id!==b.dataset.photoDel);drawPhotos()})}
  function bindForm(){
    bindNav();
    document.querySelector('[data-action="back"]').onclick=()=>{tab='home';draft=null;render()};
    document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{syncDraft();const k=b.dataset.part;draft.bodyParts=draft.bodyParts.includes(k)?draft.bodyParts.filter(x=>x!==k):[...draft.bodyParts,k];render()});
    document.querySelectorAll('[data-score]').forEach(r=>r.oninput=e=>{draft.symptoms[e.target.dataset.score]=Number(e.target.value);document.getElementById('val-'+e.target.dataset.score).textContent=e.target.value+' / 10'});
    document.getElementById('photoInput').onchange=async e=>{
      syncDraft();
      const remaining=PHOTO_LIMIT-draft.photos.length;
      if(remaining<=0){alert('사진은 최대 '+PHOTO_LIMIT+'장까지 추가할 수 있어요.');e.target.value='';return}
      const files=[...(e.target.files||[])].slice(0,remaining);
      if((e.target.files||[]).length>remaining)alert('사진은 최대 '+PHOTO_LIMIT+'장까지 저장됩니다. 초과한 사진은 제외했어요.');
      const imgs=[];
      for(const file of files){const dataUrl=await imageFileToDataUrl(file);if(dataUrl)imgs.push({id:uid('photo'),name:file.name,dataUrl})}
      draft.photos=[...draft.photos,...imgs].slice(0,PHOTO_LIMIT);
      e.target.value='';drawPhotos()
    };
    document.getElementById('saveRecord').onclick=()=>{
      syncDraft();
      if(!draft.bodyParts.length){alert('부위를 하나 이상 선택해 주세요.');return}
      const savedRecord={...draft,updatedAt:new Date().toISOString()};
      const exists=state.records.some(r=>r.id===savedRecord.id);
      state={...state,records:exists?state.records.map(r=>r.id===savedRecord.id?savedRecord:r):[{...savedRecord,createdAt:savedRecord.createdAt||new Date().toISOString()},...state.records]};
      const ok=persist();
      draft=null;detailId=null;tab='records';render();
      const successMessage=exists?'기록이 수정되었습니다.':'기록이 저장되었습니다.';
      showToast(ok?successMessage:'기록은 화면에 반영되었지만, 브라우저 저장공간 부족으로 영구 저장에 실패했을 수 있어요. 사진 수를 줄이거나 백업 후 다시 확인해 주세요.');
    }
  }
  function records(){let filter='all';const draw=()=>{const sorted=[...state.records].sort((a,b)=>new Date(b.recordedAt)-new Date(a.recordedAt));const filtered=sorted.filter(r=>filter==='severe'?(r.symptoms.itchScore>=7||r.symptoms.rednessScore>=7):filter==='medicine'?!!r.medicines.trim():true);const days={};sorted.forEach(r=>{const d=new Date(r.recordedAt);if(!isNaN(d))days[d.getDate()]=true});root.innerHTML=app(`${header('기록 보기',false,'<button class="icon-btn" id="plusBtn">+</button>')}<div class="content"><div class="row" style="overflow:auto">${[['all','전체'],['severe','심한 날'],['medicine','약 사용']].map(([k,l])=>`<button class="btn small ${filter===k?'':'outline'}" data-filter="${k}">${l}</button>`).join('')}</div><div class="card"><p class="bold" style="text-align:center;margin-bottom:14px">이번 달 기록 캘린더</p><div class="cal">${['일','월','화','수','목','금','토'].map(d=>`<div><b>${d}</b></div>`).join('')}${Array.from({length:35}).map((_,i)=>`<div><span class="day ${days[i+1]?'mark':''}">${i+1<=31?i+1:''}</span></div>`).join('')}</div></div><div class="list">${filtered.length?filtered.map(r=>`<button class="record-item" data-open="${r.id}"><div class="thumb">${r.photos?.[0]?.dataUrl?`<img src="${r.photos[0].dataUrl}">`:'▧'}</div><div class="grow"><p class="bold">${fmt(r.recordedAt)}</p><p class="small muted">${r.bodyParts.map(partLabel).join(', ')||'부위 없음'}</p><p class="tiny muted">가려움 ${r.symptoms.itchScore} · 붉음 ${r.symptoms.rednessScore}</p></div><span class="muted">›</span></button>`).join(''):'<div class="empty"><b>기록이 없습니다</b><p class="small" style="margin-top:8px">오늘 기록하기 버튼으로 첫 기록을 남겨보세요.</p></div>'}</div></div>`);document.getElementById('plusBtn').onclick=()=>{draft=emptyRecord();tab='form';render()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;draw()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{detailId=b.dataset.open;render()})};draw()}
  function detail(){const r=state.records.find(x=>x.id===detailId);if(!r){detailId=null;render();return}root.innerHTML=app(`${header('기록 상세',true,'<button class="icon-btn" id="editBtn">✎</button>')}<div class="content"><div class="report-photo" style="height:260px">${r.photos?.[0]?.dataUrl?`<img src="${r.photos[0].dataUrl}">`:'▧ 등록된 사진 없음'}</div>${r.photos?.length>1?`<div class="photos">${r.photos.slice(1).map(p=>`<div class="photo"><img src="${p.dataUrl}"></div>`).join('')}</div>`:''}<div class="card"><p class="bold">${fmt(r.recordedAt)}</p><p class="small muted" style="margin-top:8px">부위: ${r.bodyParts.map(partLabel).join(', ')}</p></div><div class="grid4">${[['가려움','itchScore'],['붉음','rednessScore'],['진물','oozeScore'],['각질','scaleScore'],['긁음','scratchScore']].map(([l,k])=>`<div class="mini-score"><span class="tiny muted bold">${l}</span><b>${r.symptoms[k]||0}</b></div>`).join('')}</div>${info('사용한 약 / 보습제',r.medicines||'-')}${info('음식 메모',r.foodMemo||'-')}${info('수면',sleepLabel(r.sleepStatus))}${info('기타 메모',r.note||'-')}<button class="btn outline" id="editMainBtn">✎ 기록 수정하기</button><button class="btn danger" id="delBtn">× 기록 삭제</button></div>`);document.querySelector('[data-action="back"]').onclick=()=>{detailId=null;render()};const startEdit=()=>{draft=JSON.parse(JSON.stringify(r));detailId=null;tab='form';render()};document.getElementById('editBtn').onclick=startEdit;document.getElementById('editMainBtn').onclick=startEdit;document.getElementById('delBtn').onclick=()=>{if(confirm('이 기록을 삭제할까요? 삭제한 기록은 복구할 수 없습니다.')){setState(s=>({...s,records:s.records.filter(x=>x.id!==r.id)}));detailId=null;tab='records';render()}};bindNav()}
  function info(t,c){return `<div class="card"><p class="small bold">${t}</p><p class="small muted" style="margin-top:8px;white-space:pre-wrap;line-height:1.6">${esc(c)}</p></div>`}
  function report(){const recs=state.records.filter(r=>inDays(r,reportRange));const sum=buildReport(recs);root.innerHTML=app(`${header('병원 리포트')}<div class="content"><div class="seg" style="background:#f1f5f9;border-radius:22px;padding:4px"><button class="choice ${reportRange===7?'active':''}" data-range="7">최근 7일</button><button class="choice ${reportRange===30?'active':''}" data-range="30">최근 30일</button></div><div class="grid2">${rCard('기록 횟수',sum.recordCount+'회','최근 '+reportRange+'일')}${rCard('가려움 평균',sum.avgItch,'/ 10')}${rCard('붉음 평균',sum.avgRedness,'/ 10')}${rCard('가장 심했던 날',sum.worstRecord?fmt(sum.worstRecord.recordedAt,true):'-',sum.worstScore?'기록 점수 '+sum.worstScore:'')}</div><div class="card"><p class="bold">많이 기록된 부위</p><p class="small muted" style="margin-top:10px">${sum.topParts.length?sum.topParts.map(x=>`${partLabel(x.key)} ${x.count}회`).join(' · '):'기록 없음'}</p></div><div class="card"><p class="bold">사진 변화</p><div class="grid2" style="margin-top:14px;align-items:center"><div>${photoCompare('첫 기록',sum.firstPhotoRecord)}</div><div>${photoCompare('최근 기록',sum.lastPhotoRecord)}</div></div></div>${textarea('보호자 메모','guardianMemo',guardianMemo,'병원에 전달하고 싶은 내용을 입력하세요.')}<div class="grid2"><button class="btn" id="txtBtn">⇩ TXT 저장</button><button class="btn outline" id="jsonBtn">▤ JSON 저장</button></div><p class="small muted card soft">현재 1차 버전은 PDF 저장 대신 TXT/JSON 저장을 제공합니다.</p></div>`);document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{reportRange=Number(b.dataset.range);guardianMemo=document.getElementById('guardianMemo')?.value||guardianMemo;render()});document.getElementById('guardianMemo').oninput=e=>guardianMemo=e.target.value;document.getElementById('txtBtn').onclick=()=>download(`skinlog-report-${reportRange}days.txt`,makeReportText(state.profile,reportRange,sum,guardianMemo,recs),'text/plain;charset=utf-8');document.getElementById('jsonBtn').onclick=()=>download(`skinlog-report-${reportRange}days.json`,JSON.stringify({app:'스킨로그 MVP',exportedAt:new Date().toISOString(),profile:state.profile,range:reportRange+'일',summary:sum,guardianMemo,records:recs,disclaimer:'사용자 입력 기록 요약이며 의학적 진단이나 치료 판단을 제공하지 않습니다.'},null,2),'application/json')}
  function rCard(t,v,s){return `<div class="card summary"><p class="tiny muted bold">${t}</p><p class="value">${esc(v)}</p><p class="tiny muted">${esc(s||'')}</p></div>`}
  function buildReport(records){const scored=records.map(r=>({record:r,score:(r.symptoms.itchScore||0)+(r.symptoms.rednessScore||0)+(r.symptoms.scratchScore||0)})).sort((a,b)=>b.score-a.score);const counts={};records.forEach(r=>r.bodyParts.forEach(p=>counts[p]=(counts[p]||0)+1));const topParts=Object.entries(counts).map(([key,count])=>({key,count})).sort((a,b)=>b.count-a.count).slice(0,3);const photos=records.filter(r=>r.photos?.length).sort((a,b)=>new Date(a.recordedAt)-new Date(b.recordedAt));return {recordCount:records.length,avgItch:avg(records.map(r=>r.symptoms.itchScore)),avgRedness:avg(records.map(r=>r.symptoms.rednessScore)),worstRecord:scored[0]?.record||null,worstScore:scored[0]?.score||0,topParts,firstPhotoRecord:photos[0]||null,lastPhotoRecord:photos[photos.length-1]||null}}
  function photoCompare(label,r){return `<div style="text-align:center"><div class="report-photo">${r?.photos?.[0]?.dataUrl?`<img src="${r.photos[0].dataUrl}">`:'▧'}</div><p class="tiny bold muted" style="margin-top:8px">${label}</p><p class="tiny muted">${r?fmt(r.recordedAt,true):'-'}</p></div>`}
  function makeReportText(profile,range,sum,memo,records){return ['스킨로그 병원 리포트','====================',`프로필: ${profile?.nickname||'-'}`,`기간: 최근 ${range}일`,`기록 횟수: ${sum.recordCount}회`,`가려움 평균: ${sum.avgItch} / 10`,`붉음 평균: ${sum.avgRedness} / 10`,`가장 심했던 날: ${sum.worstRecord?fmt(sum.worstRecord.recordedAt):'-'}`,`많이 기록된 부위: ${sum.topParts.length?sum.topParts.map(x=>`${partLabel(x.key)} ${x.count}회`).join(', '):'-'}`,'','보호자 메모',memo||'-','','기록 목록',...records.map((r,i)=>`${i+1}. ${fmt(r.recordedAt)} / 부위: ${r.bodyParts.map(partLabel).join(', ')} / 가려움 ${r.symptoms.itchScore}, 붉음 ${r.symptoms.rednessScore}, 긁음 ${r.symptoms.scratchScore} / 약: ${r.medicines||'-'} / 메모: ${r.note||'-'}`),'','면책 문구: 이 자료는 사용자가 입력한 기록을 요약한 것이며, 의학적 진단이나 치료 판단을 제공하지 않습니다.'].join('\n')}
  function settings(){root.innerHTML=app(`${header('설정')}<div class="content"><div class="card"><p class="small bold muted">현재 프로필</p><h2 style="margin-top:8px">${esc(state.profile?.nickname||'-')}</h2><p class="small muted" style="margin-top:5px">${state.profile?.type==='child'?'아이':'본인'} · ${esc(state.profile?.birthInfo||'나이대 미입력')}</p>${state.profile?.skinMemo?`<p class="small muted" style="margin-top:12px;line-height:1.6">${esc(state.profile.skinMemo)}</p>`:''}</div><div class="settings-list">${setRow('♙','프로필 관리','다음 버전에서 수정 기능 추가 예정')}${setRow('☰','기록 항목 설정','현재는 기본 항목 사용')}${setRow('◇','의료 면책 문구','진단·치료·처방 기능 없음')}</div><div class="card"><h3>데이터 백업</h3><p class="small muted" style="margin-top:8px;line-height:1.6">브라우저 데이터 삭제 또는 기기 변경 시 기록이 사라질 수 있습니다.</p><div class="grid2" style="margin-top:12px"><button class="btn" id="backupBtn">백업 저장</button><label class="btn outline">백업 불러오기<input id="importInput" type="file" accept=".json,application/json,text/plain" style="display:none"></label></div></div><div class="card soft"><p class="tiny muted" style="line-height:1.6"><b>개인정보 안내</b><br>이 프로토타입은 회원가입 없이 사용하며, 입력한 기록은 현재 브라우저 저장소에 저장됩니다. 개발자 서버로 자동 전송하지 않습니다.</p></div><button class="btn danger" id="resetBtn">모든 데이터 삭제</button></div>`);document.getElementById('backupBtn').onclick=()=>download(`skinlog-backup-${Date.now()}.json`,JSON.stringify({...state,backupType:'skinlog-backup',backupVersion:2,exportedAt:new Date().toISOString()},null,2),'application/json');document.getElementById('importInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));const restored=normalizeImport(parsed);state=restored;const ok=persist();tab='home';detailId=null;draft=null;render();alert(ok?'백업 데이터를 불러왔습니다.':'백업은 불러왔지만 브라우저 저장공간 부족으로 영구 저장에 실패했을 수 있어요.')}catch(err){console.warn(err);alert('백업 파일을 읽을 수 없습니다. 스킨로그의 백업 저장 파일(.json)을 선택했는지 확인해 주세요.')}};reader.onerror=()=>alert('파일을 읽는 중 오류가 발생했습니다.');reader.readAsText(f);e.target.value=''};document.getElementById('resetBtn').onclick=()=>{if(confirm('모든 데이터를 삭제할까요? 이 작업은 되돌릴 수 없습니다.')){localStorage.removeItem(STORAGE_KEY);state=DEFAULT;tab='home';render()}}}
  function setRow(i,t,d){return `<div class="setting-row"><div class="avatar" style="width:40px;height:40px;border-radius:16px;font-size:18px">${i}</div><div class="grow"><p class="bold">${t}</p><p class="tiny muted">${d}</p></div><span class="muted">›</span></div>`}
  function download(filename,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
  function bindNav(){/* 하단 메뉴는 root 이벤트 위임으로 처리합니다. */}
  function render(){if(!state.onboardingCompleted)return onboarding();if(!state.profile)return profile();if(detailId)return detail();if(tab==='form')return form();if(tab==='home')home();if(tab==='records')records();if(tab==='report')report();if(tab==='settings')settings();bindNav()}
  render();
})();
